import antfu, { GLOB_SRC, GLOB_TS, GLOB_TSX } from '@antfu/eslint-config'

export default antfu(
  {
    type: 'lib',
    ignores: ['**/dist', '**/esm', '**/lib', '**/bin', '.claude', '.aide'],
    pnpm: false,
    toml: false,
    regexp: false,
    vue: false,
    formatters: {
      css: true,
      html: true,
      markdown: true,
      prettierOptions: {
        endOfLine: 'lf',
        printWidth: 140,
      },
    },
    typescript: {
      tsconfigPath: 'tsconfig.json',
    },
    react: {
      overrides: {
        'react/no-unstable-default-props': 'off',
        'react/no-clone-element': 'off',
        'react/prefer-destructuring-assignment': 'off',
        'react/no-missing-key': 'error',
        'react/no-children-for-each': 'off',
        'react/jsx-key-before-spread': 'off',
        'react/no-unnecessary-use-prefix': 'off',
        'react/exhaustive-deps': ['warn', { additionalHooks: 'useIsomorphicEffect' }],
        'react-dom/no-dangerously-set-innerhtml': 'off',
        'react-dom/no-flush-sync': 'off',
        'react-dom/no-missing-button-type': 'off',
        'react-naming-convention/ref-name': 'off',
      },
    },
    stylistic: {
      overrides: {
        'style/jsx-curly-spacing': ['error', { when: 'never', children: true }],
        'style/max-statements-per-line': ['error', { max: 4 }],
        'style/no-multi-spaces': 'error',
        'style/no-extra-parens': ['error', 'all', {
          ignoreJSX: 'all',
          conditionalAssign: true,
          returnAssign: false,
          nestedBinaryExpressions: false,
          enforceForSequenceExpressions: false,
          ignoredNodes: ['ArrowFunctionExpression > ConditionalExpression'],
        }],
      },
    },
    rules: {
      'antfu/curly': 'off',
      'antfu/if-newline': 'off',
      'curly': ['error', 'multi-line'],
      'node/prefer-global/process': 'off',
      'import/order': 'off',
      'no-console': 'off',
      'no-else-return': ['error', { allowElseIf: false }],
      'eslint-comments/no-unlimited-disable': 'off',
    },
  },
  {
    files: [GLOB_TS, GLOB_TSX],
    rules: {
      'ts/explicit-function-return-type': 'off',
      'ts/strict-boolean-expressions': 'off',
      'ts/no-unsafe-assignment': 'off',
      'ts/no-unsafe-call': 'off',
      'ts/no-unsafe-member-access': 'off',
      'ts/no-unsafe-argument': 'off',
      'ts/promise-function-async': 'off',
      'ts/no-floating-promises': 'off',
      'ts/no-misused-promises': 'off',
      'ts/no-unsafe-return': 'off',
      'ts/unbound-method': 'off',
      'ts/restrict-template-expressions': 'off',
      'ts/no-unnecessary-type-assertion': 'off',
    },
  },
  {
    // 导入导出相关配置
    files: [GLOB_SRC],
    rules: {
      'perfectionist/sort-array-includes': 'off',
      'perfectionist/sort-classes': 'off',
      'perfectionist/sort-decorators': 'error',
      'perfectionist/sort-enums': 'error',
      'perfectionist/sort-imports': ['error', {
        order: 'asc',
        type: 'natural',
        newlinesBetween: 1,
        internalPattern: ['^[~@]/.+'],
        customGroups: [
          {
            groupName: 'url',
            selector: 'external',
            elementNamePattern: ['^https?://'],
            modifiers: ['value'],
          },
          {
            groupName: 'type-url',
            selector: 'external',
            elementNamePattern: ['^https?://'],
            modifiers: ['type'],
          },
          {
            groupName: 'portal',
            selector: 'external',
            elementNamePattern: ['^(?!node:).+:.+'],
            modifiers: ['value'],
          },
          {
            groupName: 'type-portal',
            selector: 'external',
            elementNamePattern: ['^(?!node:).+:.+'],
            modifiers: ['type'],
          },
          {
            groupName: 'react',
            selector: 'external',
            elementNamePattern: ['^react$', '^react/', '^react-dom', '^react-dom\\/'],
            modifiers: ['value'],
          },
          {
            groupName: 'type-react',
            selector: 'external',
            elementNamePattern: ['^react$', '^react/', '^react-dom', '^react-dom/'],
            modifiers: ['type'],
          },
          {
            groupName: 'scoped',
            selector: 'external',
            elementNamePattern: ['^@[^/]+'],
            modifiers: ['value'],
          },
          {
            groupName: 'type-scoped',
            selector: 'external',
            elementNamePattern: ['^@[^/]+'],
            modifiers: ['type'],
          },
          {
            groupName: 'assets',
            selector: 'import',
            elementNamePattern: ['\\.(jpe?g|png|gif|svg|mp4|mp3|wav|json)$'],
          },
        ],
        groups: [
          ['type-url', 'type-portal'],
          { newlinesBetween: 0 },
          ['type-subpath'],
          { newlinesBetween: 0 },
          ['type-builtin'],
          { newlinesBetween: 0 },
          ['type-external'],
          { newlinesBetween: 0 },
          ['type-react'],
          { newlinesBetween: 0 },
          ['type-scoped'],
          { newlinesBetween: 0 },
          ['type-internal'],
          { newlinesBetween: 0 },
          ['type-parent', 'type-sibling', 'type-index'],
          { newlinesBetween: 0 },
          'type-import',

          ['url', 'portal'],
          { newlinesBetween: 0 },
          ['value-subpath'],
          { newlinesBetween: 0 },
          ['value-builtin'],
          ['value-external'],
          { newlinesBetween: 0 },
          ['react'],
          { newlinesBetween: 0 },
          ['scoped'],
          ['side-effect'],
          ['value-internal'],
          { newlinesBetween: 0 },
          ['value-parent', 'value-sibling', 'value-index'],
          ['assets'],
          ['side-effect-style'],
          { newlinesBetween: 0 },
          ['style'],
          'unknown',
        ],
      }],
      'perfectionist/sort-exports': ['error', {
        order: 'asc',
        type: 'natural',
        newlinesBetween: 1,
      }],
      'perfectionist/sort-heritage-clauses': 'error',
      'perfectionist/sort-interfaces': 'off',
      'perfectionist/sort-intersection-types': 'error',
      'perfectionist/sort-jsx-props': ['error', {
        order: 'asc',
        type: 'natural',
        customGroups: [
          {
            groupName: 'unique',
            elementNamePattern: '^(key|ref)$',
          },
          {
            groupName: 'style',
            elementNamePattern: '^(className|style|classNames|styles)$',
          },
          {
            groupName: 'callback',
            elementNamePattern: '^on[A-Z]+',
          },
        ],
        groups: ['unique', 'style', 'shorthand-prop', 'unknown', 'callback'],
      }],
      'perfectionist/sort-maps': 'off',
      'perfectionist/sort-modules': 'off',
      'perfectionist/sort-objects': 'off',
      'perfectionist/sort-objects-type': 'off',
      'perfectionist/sort-sets': 'off',
      'perfectionist/sort-switch-case': 'off',
      'perfectionist/sort-union-types': 'off',
      'perfectionist/sort-variable-declarations': ['error', {
        order: 'desc',
        type: 'natural',
      }],
    },
  },
  {
    // 更新比较频繁，直接复制一遍得了
    files: ['**/tsconfig.json', '**/tsconfig.*.json'],
    rules: {
      'jsonc/sort-keys': [
        'error',
        {
          order: [
            'extends',
            'compilerOptions',
            'references',
            'files',
            'include',
            'exclude',
          ],
          pathPattern: '^$',
        },
        {
          order: [
            'incremental',
            'composite',
            'tsBuildInfoFile',
            'disableSourceOfProjectReferenceRedirect',
            'disableSolutionSearching',
            'disableReferencedProjectLoad',
            'target',
            'jsx',
            'jsxFactory',
            'jsxFragmentFactory',
            'jsxImportSource',
            'lib',
            'moduleDetection',
            'noLib',
            'reactNamespace',
            'useDefineForClassFields',
            'emitDecoratorMetadata',
            'experimentalDecorators',
            'libReplacement',
            'baseUrl',
            'rootDir',
            'rootDirs',
            'customConditions',
            'module',
            'moduleResolution',
            'moduleSuffixes',
            'noResolve',
            'paths',
            'resolveJsonModule',
            'resolvePackageJsonExports',
            'resolvePackageJsonImports',
            'typeRoots',
            'types',
            'allowArbitraryExtensions',
            'allowImportingTsExtensions',
            'allowUmdGlobalAccess',
            'allowJs',
            'checkJs',
            'maxNodeModuleJsDepth',
            'strict',
            'strictBindCallApply',
            'strictFunctionTypes',
            'strictNullChecks',
            'strictPropertyInitialization',
            'allowUnreachableCode',
            'allowUnusedLabels',
            'alwaysStrict',
            'exactOptionalPropertyTypes',
            'noFallthroughCasesInSwitch',
            'noImplicitAny',
            'noImplicitOverride',
            'noImplicitReturns',
            'noImplicitThis',
            'noPropertyAccessFromIndexSignature',
            'noUncheckedIndexedAccess',
            'noUnusedLocals',
            'noUnusedParameters',
            'useUnknownInCatchVariables',
            'declaration',
            'declarationDir',
            'declarationMap',
            'downlevelIteration',
            'emitBOM',
            'emitDeclarationOnly',
            'importHelpers',
            'importsNotUsedAsValues',
            'inlineSourceMap',
            'inlineSources',
            'mapRoot',
            'newLine',
            'noEmit',
            'noEmitHelpers',
            'noEmitOnError',
            'outDir',
            'outFile',
            'preserveConstEnums',
            'preserveValueImports',
            'removeComments',
            'sourceMap',
            'sourceRoot',
            'stripInternal',
            'allowSyntheticDefaultImports',
            'esModuleInterop',
            'forceConsistentCasingInFileNames',
            'isolatedDeclarations',
            'isolatedModules',
            'preserveSymlinks',
            'verbatimModuleSyntax',
            'erasableSyntaxOnly',
            'skipDefaultLibCheck',
            'skipLibCheck',
          ],
          pathPattern: '^compilerOptions$',
          allowLineSeparatedGroups: true,
        },
      ],
    },
  },
)
