packages:
  - apps/*
  - internals/*
  - packages/core
  - packages/shared
  - packages/icons

autoInstallPeers: true

catalog:
  '@babel/runtime': 7.28.2
  '@types/react': 19.1.17
  '@types/react-dom': 19.1.11
  '@types/react-is': 19.0.0
  classnames: 2.5.1
  react: 19.1.2
  react-dom: 19.1.2
  react-fast-compare: 3.2.2
  react-is: 19.1.2
  sass: 1.89.2

onlyBuiltDependencies:
  - esbuild

strictPeerDependencies: false
