import type { FormatXmlNodeListReturn, XmlJson } from '../../../interface'

import path from 'node:path'

import { XMLParser } from 'fast-xml-parser'

import { constants } from '../../../utils/constants'
import { capitalize, isArray, isObject, removeExtname, toArray } from '../../../utils/helpers'
import { clearIcon, toBase64, xmlToJsx } from './helpers'

/**
 * @description 格式化 xml 节点数据
 */
function formatXmlNodeList<T extends 'node' | 'attr'>(
  json: XmlJson,
  type: T,
): FormatXmlNodeListReturn<T> {
  const isCheckNode = type === 'node'

  const initialValue: any = isCheckNode ? [] : {}

  if (!isObject(json)) return initialValue

  const re = new RegExp(`^${constants.iconAttrNamePrefix}`)

  return Object.entries(json).reduce((result, [key, value]) => {
    const isJsxTag = !re.test(key)

    if (!(isCheckNode || isJsxTag)) {
      result[formatXmlAttrName(key, re)] = value

      return result
    }

    if (isJsxTag && isArray(result)) {
      toArray(value).forEach((node) => {
        result.push({
          tag: key,
          attrs: formatXmlNodeList(node, 'attr'),
          children: formatXmlNodeList(node, 'node'),
        })
      })
    }

    return result
  }, initialValue)
}

/**
 * @description 格式化 icon 文件内容
 */
export function formatXmlContent(fileContent: string, relativePath: string) {
  const kebabName = removeExtname(path.basename(relativePath))
  const iconTheme = path.dirname(relativePath)

  const iconName = formatIconName(relativePath)

  const parser = new XMLParser({
    ignoreAttributes: false,
    attributeNamePrefix: constants.iconAttrNamePrefix,
  })

  const clearedJson = parser.parse(clearIcon(fileContent).data)

  const nodeList = formatXmlNodeList(clearedJson, 'node')

  const params = nodeList[0] && nodeList[0].tag === 'svg' ? nodeList[0].attrs : {}

  const formatted = `/* eslint-disable */
// @ts-nocheck
/** This file is automatically generated, please do not manually modify it */
import type { IconProps } from '../shared/_shared.props'

import withIcon from '../shared/with-icon'
import { shallowMerge } from '@mink-ui/shared/object/shallow-merge'

function ${iconName}(_props: IconProps) {
  ${Object.keys(params).length ? `const props = shallowMerge(_props, ${JSON.stringify(params)})` : 'const props = _props'}
  return ${xmlToJsx(nodeList, 0)}
}

/** ![${kebabName}](${toBase64(fileContent)}) */
export default withIcon(${iconName}, ${JSON.stringify({ name: kebabName, theme: iconTheme })})
`

  return { iconName, formatted }
}

/**
 * @description 格式化 xml 属性名称
 */
export function formatXmlAttrName(attribute: string, re: RegExp) {
  const name = attribute
    .replace(re, '')
    .split('-')
    .map((str, index) => index === 0 ? str : capitalize(str))
    .join('')

  return name === 'class' ? 'className' : name
}

/**
 * @description 格式化 icon 名称
 */
export function formatIconName(file: string) {
  return removeExtname(path.basename(file))
    .split(/-/g)
    .concat(path.dirname(file))
    .map(capitalize)
    .join('')
}
