name: Version

on:
  push:
    branches:
      - release/**

permissions:
  contents: write
  actions: write
  pull-requests: write

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        node-version: [20.18.1]
        pnpm-version: [9.12.3]

    steps:
      # checkout
      - name: Checkout Branch
        uses: actions/checkout@v4

      # 安装 pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          version: ${{ matrix.pnpm-version }}

      # 设置 node
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      # 安装依赖
      - name: Install Dependencies
        run: pnpm install

      # 设置 git 账户
      - name: Setup Git Account
        run: |
          git config user.name "clearink"
          git config user.email "1561939638@qq.com"

      # 生成更新版本的 PR
      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: pnpm run ci:version
          commit: 'chore: update versions'
          title: 'chore: update versions'
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ secrets.CLEARINK_GITHUB_TOKEN }}
